[server]
headless = true
enableCORS = false
fileWatcherType = "none"
enableStaticServing = false

[theme]
primaryColor = "#1e3a8a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[runner]
magicEnabled = false

[client]
showErrorDetails = true
